package com.example.taptalk.aac.data

import android.content.Context
import com.example.taptalk.normalizeFileName
import java.io.File

/**
 * Loads all AAC (Augmentative and Alternative Communication) cards from the app's assets.
 *
 * This function recursively scans two specific directories within the assets folder: "ACC_board" and "categories".
 * It identifies all `.png` and `.jpg` image files within these directories and their subdirectories.
 * For each image found, it creates an [AccCard] object, extracting metadata like the file name, a normalized label,
 * the asset path, and the category (derived from the parent folder name).
 *
 * The function utilizes a nested recursive helper function `walk` to traverse the directory structure.
 *
 * @param context The application context, used to access the `AssetManager`.
 * @return A list of [AccCard] objects representing all the predefined AAC images found in the assets.
 */
fun loadAccCards(context: Context): List<AccCard> {
    val assetManager = context.assets

    fun walk(path: String, topCategory: String? = null): List<AccCard> {
        val files = assetManager.list(path) ?: return emptyList()

        return files.flatMap { name ->
            val fullPath = if (path.isEmpty()) name else "$path/$name"
            val children = assetManager.list(fullPath) ?: emptyArray()

            if (children.isNotEmpty()) {
                val cat = topCategory ?: name
                walk(fullPath, cat)
            }
            else if (name.endsWith(".png") || name.endsWith(".jpg")) {
                val category = topCategory ?: path.substringAfterLast("/")
                listOf(
                    AccCard(
                        fileName = name,
                        label = normalizeFileName(name),
                        path = "file:///android_asset/$fullPath",
                        folder = category.lowercase()
                    )
                )
            }
            else emptyList()
        }
    }

    return walk("ACC_board") + walk("categories")
}

/**
 * Loads custom AAC cards created by the user from the application's internal storage.
 *
 * This function scans the `Custom_Words` directory within the app's private files
 * for image files (`.jpg` or `.png`). For each image found, it creates an [AccCard] object.
 * The card's label is derived from the file name (without extension) with the first letter capitalized.
 * The card's folder is determined by the name of its parent directory.
 *
 * @param context The application context, used to access the app's internal file storage.
 * @return A list of [AccCard] objects representing the custom cards. Returns an empty list
 *         if the `Custom_Words` directory does not exist or contains no valid image files.
 */
fun loadCustomCards(context: Context): List<AccCard> {
    val rootDir = File(context.filesDir, "Custom_Words")
    if (!rootDir.exists()) return emptyList()

    val customCards = mutableListOf<AccCard>()

    rootDir.walkTopDown().forEach { file ->
        if (file.isFile && (file.extension == "jpg" || file.extension == "png")) {
            val folderName = file.parentFile?.name ?: "custom"
            val label = file.nameWithoutExtension
            customCards.add(
                AccCard(
                    fileName = file.name,
                    label = label.replaceFirstChar { it.uppercase() },
                    path = file.absolutePath,
                    folder = folderName
                )
            )
        }
    }

    return customCards
}

/**
 * Trims a category file name to create a human-readable label.
 *
 * This function performs the following transformations:
 * 1. Removes the file extension (e.g., ".png", ".jpg").
 * 2. Removes "_cathegory" or "_category" suffixes, case-insensitively.
 * 3. Replaces all underscores with spaces.
 * 4. Trims any leading or trailing whitespace.
 * 5. Capitalizes the first character of the resulting string.
 *
 * For example, "nouns_category.png" becomes "Nouns".
 *
 * @param fileName The raw file name of the category image (e.g., "nouns_category.png").
 * @return A cleaned and capitalized category name suitable for display.
 */
fun trimCategoryName(fileName: String): String {
    var name = fileName.substringBeforeLast('.')
    name = name.replace("_cathegory","",true)
        .replace("_category","",true)
        .replace("_"," ")
        .trim()
    return name.replaceFirstChar { it.uppercase() }
}

/**
 * Loads predefined ACC category cards from the "ACC_board/categories" asset directory.
 *
 * This function reads image files from the specified asset subfolder, sorts them according
 * to a predefined `desiredOrder` list, and maps them to a list of [AccCard] objects.
 * The label for each card is generated by cleaning up the filename (e.g., removing "_category"
 * and replacing underscores with spaces).
 *
 * If the asset directory does not exist or is empty, it returns an empty list.
 *
 * @param context The application context, used to access the `assets` directory.
 * @return A [List] of [AccCard] objects representing the categories, sorted in a specific predefined order.
 */
fun loadCategories(context: Context): List<AccCard> {
    val files = context.assets.list("ACC_board/categories") ?: return emptyList()

    val desiredOrder = listOf(
        "home_category.png",
        "favourites_category.png",
        "custom_category.png",
        "emergency_category.png",
        "social_category.png",
        "questions_category.png",
        "pronouns_category.png",
        "nouns_category.png",
        "verbs_category.png",
        "adjective_category.png",
        "adverb_category.png",
        "prepositions_category.png",
        "conjuction_category.png",
        "determiners_category.png",
        "negation_category.png"
    )

    val sortedFiles = desiredOrder.mapNotNull { orderName ->
        files.find { it.equals(orderName, ignoreCase = true) }
    }

    return sortedFiles.map { file ->
        AccCard(
            fileName = file,
            label = trimCategoryName(file),
            path = "file:///android_asset/ACC_board/categories/$file",
            folder = "categories"
        )
    }
}
