package com.example.taptalk.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single entry in the conversation history table.
 *
 * This data class is used by Room to define the "history" table schema. Each instance
 * corresponds to a row in the table, storing a spoken or typed sentence along with a
 * timestamp.
 *
 * @property id The unique identifier for the history entry. This is auto-generated by the database.
 * @property sentence The text content of the sentence that was recorded.
 * @property timestamp The time the entry was created, in milliseconds since the Unix epoch.
 */
@Entity(tableName = "history")
data class HistoryEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val sentence: String,
    val timestamp: Long = System.currentTimeMillis()
)
